services:
  confessy :
    build:
      context: .
      dockerfile: Dockerfile
    container_name: confessy
    volumes:
      - ./src/database:/app/src/database
      - /auth_info:/app/auth_info
    restart: always
    ports:
      - "0.0.0.0:8081:8081"
    env_file:
      - .env
